// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Hand-written guides. The generated API reference lives in its own sidebar
  // (below) so it does not flood this one.
  tutorialSidebar: [
    'intro',
    {type: 'category', label: 'Getting started', collapsed: false, items: [{type: 'autogenerated', dirName: 'getting-started'}]},
    {type: 'category', label: 'Authentication', items: [{type: 'autogenerated', dirName: 'authentication'}]},
    {type: 'category', label: 'Basics', items: [{type: 'autogenerated', dirName: 'basics'}]},
    {type: 'category', label: 'Helpers', items: [{type: 'autogenerated', dirName: 'helpers'}]},
    {type: 'category', label: 'Advanced', items: [{type: 'autogenerated', dirName: 'advanced'}]},
    'support',
  ],

  // gotd/botapi — the Telegram Bot API surface over MTProto. Its own sidebar so
  // it stays distinct from the low-level client tutorial.
  botapiSidebar: [{type: 'autogenerated', dirName: 'botapi'}],

  // Generated API reference (tools/docgen).
  referenceSidebar: [{type: 'autogenerated', dirName: 'reference'}],
};

module.exports = sidebars;
