# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: 'Getting started'
  link: '/getting-started'
- label: Examples
  items:
    - label: 'Echo bot'
      link: '/example/echo-bot'
- label: Community
  items:
    - label: 'Github'
      link: https://github.com/gotd/td
- label: 'Security Policy'
  link: '/security'
